  name: Selenium_RUN
  on: [push, workflow_dispatch]
  jobs:
    testing_the_website:
      runs-on: ubuntu-latest
      steps:
      - name: Get the repository code
        uses: actions/checkout@v4.1.1
      - name: install Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'
      - name: installing necessary pip's
        run: pip install pytest selenium webdriver-manager allure-pytest
      - name: installing chrome...
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome
      - name: Run tests
        run: pytest



#      - name: What installed
#        run: pip list
#      - name: py version
#        run: python --version
#      - name:
#      - name:
