  name: Selenium_RUN
  on: [push, workflow_dispatch]
  jobs:
    testing_the_website:
      runs-on: windows-latest
      steps:
      - name: Get the repository code
        uses: actions/checkout@v4.1.1

      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~\npm\cache\_cacache
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: install an allure dashboard
        run: npm ci

      - run:  npm --global cache verify

#      - name: install Python
#        uses: actions/setup-python@v4.7.1
#        with:
#          python-version: '3.12'
#          cache: 'pip' # caching pip dependencies
#      - run: pip install -r requirements.txt
#      - name: set up the Chrome
#        uses: browser-actions/setup-chrome@v1
#        with:
#          chrome-version: stable
#        id: setup-chrome
#      - name: Run tests
#        run: pytest --alluredir .\dashboard\