  name: Selenium_RUN
  on: [push, workflow_dispatch]
  jobs:
    testing_the_website:
      runs-on: windows-latest
      steps:
      - name: Get the repository code
        uses: actions/checkout@v4.1.1
      - name: install Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - name: Run tests
        run: pytest